name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r .ai/io/nerdythings/requirements.txt

      - name: Get previous commit (for push events)
        if: github.event_name == 'push'
        run: echo "BASE_REF=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

      - name: Run AI Reviewer
        env:
          CHATGPT_KEY: ${{ secrets.CHATGPT_KEY }}
          CHATGPT_MODEL: ${{ secrets.CHATGPT_MODEL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_EXTENSIONS: ${{ vars.TARGET_EXTENSIONS }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          BASE_REF: ${{ github.event.pull_request.base.sha || env.BASE_REF }}
          HEAD_REF: ${{ github.event.pull_request.head.sha || github.sha }}
          PULL_NUMBER: ${{ github.event.pull_request.number || '' }}
        run: |
          python .ai/io/nerdythings/github_reviewer.py

      - name: Debug Environment Variables
        run: |
            echo "GITHUB_EVENT_NAME=${{ github.event_name }}"
            echo "PULL_NUMBER=${{ github.event.pull_request.number }}"